from . import condo_water_reading
from . import condo_residence
from . import condo_visitor
from . import res_partner
from . import condo_residence_tags
from . import condo_residence_pets
from . import condo_residence_vehicles
from . import condominio_recurring_visitor
from . import wizard_water_report
from . import report_water_reading
from . import wizard_import_water