version: "2.4"

# volumes:
#   filestore:
#     driver: local
#     driver_opts:
#       o: bind
#       type: volume
#       device: /home/publico/desenv/odoo/odoo12/local/filestore

services:
  odoo:
    build:
      context: ./odoo
      args:
        ODOO_VERSION: "14.0"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    environment:
      EMAIL_FROM: ""
      PGHOST: "127.0.0.1"
      PGDATABASE: &dbname 22_ocb14a
      PGUSER: &dbuser "odoo"
      PROXY_MODE: "false"
      LIST_DB: "true"
    tty: true
    volumes:
      # - type: volume
      #   source: filestore
      #   target: /home/publico/tmp
      #   volume:
      #     nocopy: true
      - type: bind
        source: /home/publico/desenv/odoo/odoo12/local/filestore
        target: /var/lib/odoo/filestore

  # db:
  #   image: ghcr.io/tecnativa/postgres-autoconf:13-alpine
  #   shm_size: 4gb
  #   environment:
  #     POSTGRES_DB: *dbname
  #     POSTGRES_USER: *dbuser
  #     CONF_EXTRA: |
  #       work_mem = 512MB
  #   volumes:
  #     - db:/var/lib/postgresql/data:z

  # smtpfake:
  #   image: docker.io/mailhog/mailhog
