# Author: Carlos Silveira
# Copyright 2022 ATSTi
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
{
    "name": "Cash Flow Reports",
    "version": "14.0.1.0.0",
    "category": "Reporting",
    "summary": "Financial Reports",
    "author": "ATSTi Soluções,"
    "Odoo Community Association (OCA)",
    "website": "",
    "depends": ["account", "date_range", "report_xlsx"],
    "data": [
        "security/ir.model.access.csv",
        # "wizard/aged_partner_balance_wizard_view.xml",
        # "wizard/general_ledger_wizard_view.xml",
        # "wizard/journal_ledger_wizard_view.xml",
        "wizard/cash_flow_wizard_view.xml",
        # "wizard/trial_balance_wizard_view.xml",
        # "wizard/vat_report_wizard_view.xml",
        "menuitems.xml",
        "reports.xml",
        "report/templates/layouts.xml",
        # "report/templates/aged_partner_balance.xml",
        # "report/templates/general_ledger.xml",
        # "report/templates/journal_ledger.xml",
        "report/templates/cash_flow.xml",
        # "report/templates/trial_balance.xml",
        # "report/templates/vat_report.xml",
        # "view/account_view.xml",
        "view/report_template.xml",
        # "view/report_general_ledger.xml",
        # "view/report_journal_ledger.xml",
        # "view/report_trial_balance.xml",
        "view/report_cash_flow.xml",
        # "view/report_aged_partner_balance.xml",
        # "view/report_vat_report.xml",
    ],
    "qweb": ["static/src/xml/report.xml"],
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "AGPL-3",
}
